name = "Villa Prenc"
license = "CC 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Villa Prenc"
homepage = "https://github.com/your-identity/hugo-theme-dimension/"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "minimal", "personal", "responsive", "simple"]
features = ["blog", "syntax highlighting"]
min_version = 0.54

[author]
  name = "PRENC"
  homepage = "prencdino@gmail.com"

[original]
    author = "HTML5UP"
    homepage = "https://html5up.net"

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true