name = "Villa Prenc"
title = "Villa Prenc"
license = "CC 3.0"
languageCode = "en"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Villa Prenc Matulji Croatia, beautiful villa on adriatic coast"
homepage = "https://github.com/your-identity/hugo-theme-dimension/"
tags = ["blog", "clean", "dark", "highlighting", "minimal", "personal", "responsive", "simple", "villa", "prenc", "matulji", "opatija", "croatia", "luxury"]
features = ["blog", "syntax highlighting"]
min_version = 0.54
googleAnalytics = "G-VWC6EQKS7H"

[author]
  name = "PRENC"
  homepage = "prencdino@gmail.com"

[original]
    author = "HTML5UP"
    homepage = "https://html5up.net"

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true